
package userinterface.partyRadar.EventManagerRole;

import Business.Campus.Campus;
import Business.Enterprise.Enterprise;
import Business.Group.EventManagerGroup;
import Business.Group.Group;
import Business.InformationQueue.EventPost;
import Business.InformationQueue.InformationPost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.venueRadar.VenueMaintainanceManagerRole.RequestMaintainancePanel;




/**
 *
 * @author
 */
public class CreateEventPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private EventManagerGroup group;
    private Campus campus;

    /**
    /** Creates new form BrowseProducts */
    public CreateEventPanel(JPanel userProcessContainer, UserAccount account, EventManagerGroup group, Enterprise enterprise, Campus campus) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.campus = campus;
        valueLabel.setText(enterprise.getName());
    
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEventDetails = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Event Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 30));

        txtAreaEventDetails.setColumns(20);
        txtAreaEventDetails.setRows(5);
        jScrollPane1.setViewportView(txtAreaEventDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 280, 130));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setText("Date (dd/MM/yyyy)");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 30));

        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });
        add(txtEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 280, 30));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 280, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 90, -1));

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 700, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Number Attendees");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, ""));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 280, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setText("Create Event");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 150, -1));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventManagerWorkAreaPanel emwajp = (EventManagerWorkAreaPanel) component;
        emwajp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try{   
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//            int attendees = Integer.parseInt(txtNumberAttendees.getText());
            dateFormat.setLenient(false);

            String eventName = txtEventName.getText();
            String date = txtDate.getText();

            if (eventName.isEmpty()||date.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please add all the mandatory fields!");
                } 
            else {   
                Date eventDate = dateFormat.parse(date); 
                Date now = new Date();
                if (eventDate.getTime() < now.getTime()) {
                    JOptionPane.showMessageDialog(null, "Time cannot be past！");
                    return;
                }
                InformationPost ePost = new EventPost();
                ePost.setMessage(eventName);
                ((EventPost) ePost).setEventName(eventName);
                ePost.setDate(eventDate);
                ePost.setSender(account);
                ePost.setStatus("Event Created");
//                ((EventPost)ePost).setPicPath(lblPicPath.getText());
                ((EventPost)ePost).setNumberAttendees(Integer.parseInt(jSpinner1.getValue().toString()));
                ((EventPost)ePost).setAvailableSpot(Integer.parseInt(jSpinner1.getValue().toString()));
                ((EventPost)ePost).setDetails(txtAreaEventDetails.getText());
//                ((EventPost) post).setStatus("Created");
//                ((EventPost) post).setNumberAttendees(attendees);


                Group gro = null;
                for (Group group : enterprise.getGroupDirectory().getGroupList()){
                    if (group instanceof EventManagerGroup){
                        gro = group;
                        break;
                    }
                }
                if (gro!=null){
                    gro.getInfoQueue().getInfoPostList().add(ePost);
                    account.getInfoQueue().getInfoPostList().add(ePost);
                }
                JOptionPane.showMessageDialog(null, "Event successfully created!");
                
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add("BrowseVenuePanel", new BrowseVenuePanel(userProcessContainer,account, group, enterprise, campus, txtDate.getText(),ePost));
                layout.next(userProcessContainer);
            }
        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Please follow valide date format!");
        }

        
        
        //txtVenue.setText(null);
//        txtNumberAttendees.setText(null);
        //txtAreaEventDetails.setText(null);
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser(); //set up a Jfilechooser when clicking the button
        int returnVal = fc.showOpenDialog(null);    
        
        if (returnVal == fc.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
//            txtPath.setText(path);
//            lblPicPath.setText(path);
            ImageIcon imgIcon = new ImageIcon(path);
            Image img = imgIcon.getImage();
            Image smallImg = img.getScaledInstance(100,100,Image.SCALE_DEFAULT);
            ImageIcon Icon = new ImageIcon(smallImg);
//            lblImagePreview.setIcon(Icon);

  
        } else {
            JOptionPane.showMessageDialog(null,"Open command cancelled");
        }
        
        
    }                                             

    private void btnAddPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPicActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTable productTable2;
    private javax.swing.JTextArea txtAreaEventDetails;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
