/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.partyRadar.EventManagerRole;

import Business.Campus.Campus;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PartyRadarEnterprise;
import Business.Group.CateringManagerGroup;
import Business.InformationQueue.EventPost;
import Business.InformationQueue.InformationPost;
import Business.Group.EventManagerGroup;
import Business.InformationQueue.VenueRequestPost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class EventManagerWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EventManagerGroup eventManagerGroup;
    private Enterprise enterprise;
    private UserAccount account;
    private Campus campus;
    private CateringManagerGroup cateringManagerGroup;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public EventManagerWorkAreaPanel(JPanel userProcessContainer, UserAccount account, EventManagerGroup eventManagerGroup, Enterprise enterprise, Campus campus) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.eventManagerGroup = eventManagerGroup;
        this.enterprise = enterprise;
        this.account = account;
        this.campus = campus;
//        valueLabel.setText(enterprise.getName());
        populateTable();
        valueLabel.setText(enterprise.getName());
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblEvent.getModel();
        
        model.setRowCount(0);
        for (InformationPost post : account.getInfoQueue().getInfoPostList()){
            if (post instanceof EventPost){
                Object[] row = new Object[5];
                row[0] = post;
                row[1] = post.getId();
                row[2] = post.getStatus();
                if (((EventPost)post).getvPost() != null){
                    row[3] = ((EventPost)post).getvPost().getStatus();
                }
                else{
                    row[3] = "Pending";
                }
                
                if (((EventPost)post).getcPost().getStatus() != null){
                    row[4] = ((EventPost)post).getcPost().getStatus();
                }
                else{
                    row[4] = "Pending";
                } 
                

            model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewDetails = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        btnCreateEvent = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        btnDeleteEvent = new javax.swing.JButton();
        lblHeader2 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, -1));

        tblEvent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event Name", "# Attendees", "Event Status", "Venue Status", "Catering Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEvent);
        if (tblEvent.getColumnModel().getColumnCount() > 0) {
            tblEvent.getColumnModel().getColumn(0).setResizable(false);
            tblEvent.getColumnModel().getColumn(1).setResizable(false);
            tblEvent.getColumnModel().getColumn(1).setPreferredWidth(6);
            tblEvent.getColumnModel().getColumn(2).setResizable(false);
            tblEvent.getColumnModel().getColumn(3).setResizable(false);
            tblEvent.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 600, 340));

        btnCreateEvent.setText("Create Event");
        btnCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEventActionPerformed(evt);
            }
        });
        add(btnCreateEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, -1, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader.setText("Event Manager Work Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        btnDeleteEvent.setText("Delete Event");
        btnDeleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEventActionPerformed(evt);
            }
        });
        add(btnDeleteEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 110, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        
        int row = tblEvent.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        InformationPost post = (InformationPost)tblEvent.getValueAt(row, 0);
        ViewEventPanel pnl = new ViewEventPanel(userProcessContainer, post, campus, enterprise);
        userProcessContainer.add("ViewEventPanel", pnl);        
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEventActionPerformed
        // TODO add your handling code here:
        CreateEventPanel createEventPanel = new CreateEventPanel(userProcessContainer, account, eventManagerGroup, enterprise, campus);
        userProcessContainer.add("CreateEventPanel", createEventPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        

    }//GEN-LAST:event_btnCreateEventActionPerformed

    private void btnDeleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEventActionPerformed
        int row = tblEvent.getSelectedRow();
        if(row>=0) {
            int i = JOptionPane.showConfirmDialog(null, "Are you sure to delete this event?");
            if (i == JOptionPane.YES_OPTION){
                InformationPost post = (InformationPost) tblEvent.getValueAt(row, 0); 
             //   InformationPost vPost = new VenueRequestPost();
//                ePost.getDate();
//                cateringManagerGroup.getInfoQueue().getInfoPostList().remove(ePost);
                ((EventPost)post).getcPost().setStatus("Canceled");
                ((EventPost)post).getvPost().setStatus("Canceled");
                post.setStatus("Canceled");
//                eventManagerGroup.getInfoQueue().getInfoPostList().remove(post);
//                account.getInfoQueue().getInfoPostList().remove(post); 
              //  ((EventPost)ePost).getcPost().getMessage();
                //account.getInfoQueue().getInfoPostList();
                
                //((PartyRadarEnterprise)enterprise).getInfoQueue().getInfoPostList().remove(i);
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnDeleteEventActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEvent;
    private javax.swing.JButton btnDeleteEvent;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTable tblEvent;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
