/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.partyRadar.EventManagerRole;

import Business.Campus.Campus;
import Business.Enterprise.Enterprise;
import Business.Group.EventManagerGroup;
import Business.Group.Group;
import Business.InformationQueue.EventPost;
import Business.InformationQueue.InformationPost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author
 */
public class ViewEventPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private InformationPost infoPost;
    private EventManagerGroup group;
    private Campus campus;
    
    /** Creates new form BrowseProducts */
    public ViewEventPanel(JPanel userProcessContainer, InformationPost post, Campus campus, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.infoPost = post;
        this.campus = campus;
        this.enterprise = enterprise;
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        dateFormat.setLenient(false);
        
        String eventName = post.getMessage();
        Date date = post.getDate();
        
        String details = ((EventPost) post).getDetails();
        
        String location = null;
        if (((EventPost) post).getvPost().toString() == null){
            location = "Pending";
        }
        else{
            location = ((EventPost) post).getvPost().toString();

        }
        
        int attendees = ((EventPost) post).getNumberAttendees();

        
        txtEventName.setText(eventName);
        txtDate.setText(dateFormat.format(date));
        txtLocation.setText(location);
        txtAreaEventDetails.setText(details);
        valueLabel.setText(enterprise.getName());
        txtNumberAttendees.setText(Integer.toString(attendees));       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEventDetails = new javax.swing.JTextArea();
        txtEventName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblImagePreview = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumberAttendees = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 90, -1));

        btnSave.setFont(new java.awt.Font("Al Bayan", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 80, -1));

        btnEdit.setFont(new java.awt.Font("Al Bayan", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Event Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Venue");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 100, 30));

        txtAreaEventDetails.setColumns(20);
        txtAreaEventDetails.setRows(5);
        txtAreaEventDetails.setBorder(null);
        txtAreaEventDetails.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaEventDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 190));

        txtEventName.setEnabled(false);
        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });
        add(txtEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, 30));

        txtDate.setEnabled(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 250, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 100, 30));

        txtLocation.setEnabled(false);
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 250, 30));
        add(lblImagePreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 190, 140));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Date");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 100, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel1.setText("dd/MM/yyyy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        txtNumberAttendees.setEnabled(false);
        add(txtNumberAttendees, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 250, 30));

        jLabel2.setText("Number Attendees");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader.setText("Event Deails Review");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);

//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        EventManagerWorkAreaPanel emwajp = (EventManagerWorkAreaPanel) component;
//        emwajp.populateTable();
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
        
        Component[] components = userProcessContainer.getComponents();
        for (Component c: components){
            if (c instanceof EventManagerWorkAreaPanel){
                EventManagerWorkAreaPanel panel = (EventManagerWorkAreaPanel)c;
                panel.populateTable();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{   
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            int attendees = Integer.parseInt(txtNumberAttendees.getText());
            dateFormat.setLenient(false);

            String eventName = txtEventName.getText();
            String date = txtDate.getText();

            if (eventName.isEmpty()||date.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please add all the mandatory fields!");
            } 
            else {              
                Date eventDate = dateFormat.parse(date); 
               // InformationPost ePost = new EventPost();
                infoPost.setMessage(eventName);
               ((EventPost) infoPost).setEventName(eventName);
                infoPost.setDate(eventDate);
//                ePost.setSender(account);
//                ePost.setStatus("Event Created");
//                ((EventPost) post).setStatus("Created");
                ((EventPost) infoPost).setNumberAttendees(attendees);


              //  Group gro = null;
//                for (Group group : enterprise.getGroupDirectory().getGroupList()){
//                    if (group instanceof EventManagerGroup){
////                        gro = group;
////                        break;
//                                     }
//                }
//                if (gro!=null){
//                    group.getInfoQueue().getInfoPostList().add(ePost);
//                    account.getInfoQueue().getInfoPostList().add(ePost);
//                }
                JOptionPane.showMessageDialog(null, "Event successfully edited!");
                txtEventName.setEnabled(false);
     //           txtDate.setEnabled(false);
   //             txtLocation.setEnabled(false);
                txtNumberAttendees.setEnabled(false);
                txtAreaEventDetails.setEnabled(false);
 //               btnBrowse.setEnabled(false);
//                btnChooseFile.setEnabled(false);
                btnSave.setEnabled(false); 
                btnEdit.setEnabled(true);
            }
        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Please follow valide date format!");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtEventName.setEnabled(true);
    //    txtDate.setEnabled(true);
    //    txtLocation.setEnabled(true);
        txtNumberAttendees.setEnabled(true);
        txtAreaEventDetails.setEnabled(true);
     //   btnBrowse.setEnabled(true);
//        btnChooseFile.setEnabled(true);

        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);

    }//GEN-LAST:event_btnEditActionPerformed

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JTable productTable2;
    private javax.swing.JTextArea txtAreaEventDetails;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtNumberAttendees;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
