/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.Agency;

import Business.Airliner;
import UserInterface.Agency.Airliner.ManageAirlinersJPanel;
import Business.AirlinerDirectory;
import UserInterface.Agency.FlightSchedule.MasterFlightJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Rushabh
 */
public class AgencyWorkAreaJPanel extends javax.swing.JPanel {
    JPanel container;
    Airliner airliner;
    AirlinerDirectory airlinerDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AgencyWorkAreaJPanel(JPanel c, AirlinerDirectory ad) {
        initComponents();
        container = c;
        airlinerDirectory = ad;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageTravelSche = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageAirliner1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageTravelSche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageTravelSche.setText("View Travel Schedule >>");
        btnManageTravelSche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTravelScheActionPerformed(evt);
            }
        });
        add(btnManageTravelSche, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        btnManageAirliner1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageAirliner1.setText("Manage Airliner >>");
        btnManageAirliner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirliner1ActionPerformed(evt);
            }
        });
        add(btnManageAirliner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageTravelScheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTravelScheActionPerformed
        // TODO add your handling code here:
        MasterFlightJPanel mfjp = new MasterFlightJPanel(container, airlinerDirectory);
       container.add("MasterFlightJPanel", mfjp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManageTravelScheActionPerformed

    private void btnManageAirliner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirliner1ActionPerformed
        // TODO add your handling code here:
        ManageAirlinersJPanel majp = new ManageAirlinersJPanel(container, airlinerDirectory);
        container.add("ManageAirlinersJPanel",majp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManageAirliner1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAirliner1;
    private javax.swing.JButton btnManageTravelSche;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
