/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.partyRadar.memberRole;

import Business.Campus.Campus;
import Business.CampusParty;
import Business.Enterprise.Enterprise;
import Business.InformationQueue.EventPost;
import Business.InformationQueue.InvitationPost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author
 */
public class InvitePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Campus campus;
    private CampusParty business;
    private EventPost ePost;
    /** Creates new form BrowseProducts */
    
    public InvitePanel(JPanel userProcessContainer, Enterprise enterprise, EventPost ePost, UserAccount userAccount, CampusParty business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.campus = campus;
        this.business = business;
        this.ePost = ePost;
        
        lblName.setText(userAccount.getMember().getName());
        lblVenue.setText(String.valueOf(userAccount.getFollowerList().size()));
        lblAvailableSpots.setText(String.valueOf(userAccount.getFollowingList().size()));
        
        populateFollowers();
        populate();
        
    }
    
    private void populate(){
        
        lblName.setText(ePost.toString());
        lblVenue.setText(ePost.getvPost().toString());
        lblAvailableSpots.setText(String.valueOf(ePost.getAvailableSpot())); 
            
        }
    

   
    
    private void populateFollowers(){
        DefaultTableModel model = (DefaultTableModel)tblFollower.getModel();
        model.setRowCount(0);
            
        for (UserAccount u: userAccount.getFollowerList()){
        Object[] row = new Object[2];
        row[0] = u;

        model.addRow(row);                
        }       
    }
      
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblVenue = new javax.swing.JLabel();
        btnInvite = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblAvailableSpots = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblFollower = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader3 = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/return-arrow.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 90, -1));

        lblVenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVenue.setForeground(new java.awt.Color(102, 102, 102));
        lblVenue.setText("<#>");
        add(lblVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 30, -1));

        btnInvite.setBackground(new java.awt.Color(245, 245, 245));
        btnInvite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInvite.setForeground(new java.awt.Color(255, 255, 255));
        btnInvite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/paper-plane.png"))); // NOI18N
        btnInvite.setBorder(null);
        btnInvite.setBorderPainted(false);
        btnInvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviteActionPerformed(evt);
            }
        });
        add(btnInvite, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 50, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(51, 51, 51));
        lblHeader.setText("Invite your followers together with you @");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 150, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("<show Name>");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Event");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, -1));

        lblAvailableSpots.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAvailableSpots.setForeground(new java.awt.Color(102, 102, 102));
        lblAvailableSpots.setText("<#>");
        add(lblAvailableSpots, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 30, -1));

        tblFollower.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblFollower.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Followers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFollower.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane9.setViewportView(tblFollower);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 520, 250));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Venue");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Available Spots");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 20));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/conncection.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 120, 30));

        lblHeader3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader3.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviteActionPerformed
        // TODO add your handling code here:

        
        int selectRow = tblFollower.getSelectedRow();
        if (selectRow <0){
            JOptionPane.showMessageDialog(null, "Please select a connection first!");
        }
        else{

            UserAccount selectUser = (UserAccount) tblFollower.getValueAt(selectRow, 0);
                                
            InvitationPost iPost = new InvitationPost();
            iPost.setPost(ePost);
            iPost.setSender(userAccount);
            iPost.setStatus("Sent");
            iPost.setReceiver(selectUser);
            
            selectUser.getInfoQueue().getInfoPostList().add(iPost);                       
            userAccount.getInfoQueue().getInfoPostList().add(iPost);
            
            JOptionPane.showMessageDialog(null, "Invitation successfully sent!");         
        }

    }//GEN-LAST:event_btnInviteActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInvite;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblAvailableSpots;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblVenue;
    private javax.swing.JTable productTable2;
    private javax.swing.JTable tblFollower;
    // End of variables declaration//GEN-END:variables
}
