/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.partyRadar.memberRole;




import Business.Campus.Campus;
import Business.CampusParty;
import Business.Enterprise.Enterprise;
import Business.Group.PlatformMemberGroup;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Rushabh
 */
public class MemberWelcomePage extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PlatformMemberGroup memberGroup;

    private Enterprise enterprise;
    private UserAccount userAccount;
    private CampusParty business;
    private Campus campus;
    /** Creates new form BrowseProducts */

    public MemberWelcomePage(JPanel userProcessContainer, UserAccount account, PlatformMemberGroup group, Enterprise enterprise, Campus campus, CampusParty business) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.memberGroup = group;
        this.enterprise = enterprise;
        this.business = business;
        this.campus = campus;
        
        
    }  


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnBrowseEvent = new javax.swing.JButton();
        lblCover = new javax.swing.JLabel();
        btnMessageBox = new javax.swing.JButton();
        btnViewMyPage = new javax.swing.JButton();
        lblHeader3 = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBrowseEvent.setBackground(new java.awt.Color(245, 245, 245));
        btnBrowseEvent.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnBrowseEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/compass.png"))); // NOI18N
        btnBrowseEvent.setBorder(null);
        btnBrowseEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseEventActionPerformed(evt);
            }
        });
        add(btnBrowseEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 160, 40));

        lblCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/cv.png"))); // NOI18N
        lblCover.setText("Cover");
        add(lblCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 650, 420));

        btnMessageBox.setBackground(new java.awt.Color(245, 245, 245));
        btnMessageBox.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnMessageBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/contact.png"))); // NOI18N
        btnMessageBox.setBorderPainted(false);
        btnMessageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageBoxActionPerformed(evt);
            }
        });
        add(btnMessageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 160, 40));

        btnViewMyPage.setBackground(new java.awt.Color(245, 245, 245));
        btnViewMyPage.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnViewMyPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/user_1.png"))); // NOI18N
        btnViewMyPage.setBorder(null);
        btnViewMyPage.setBorderPainted(false);
        btnViewMyPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyPageActionPerformed(evt);
            }
        });
        add(btnViewMyPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 160, 40));

        lblHeader3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader3.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseEventActionPerformed

        BrowseEvents browseEvents = new BrowseEvents(userProcessContainer, enterprise, userAccount, business);
        userProcessContainer.add("BrowseEvents", browseEvents);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnBrowseEventActionPerformed

    private void btnMessageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageBoxActionPerformed

        MessageBoxPanel mbP = new MessageBoxPanel(userProcessContainer, userAccount, enterprise, business);
        userProcessContainer.add("MessageBoxPanel", mbP);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMessageBoxActionPerformed

    private void btnViewMyPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyPageActionPerformed
        // TODO add your handling code here:
 
        ViewMyPage vmP = new ViewMyPage(userProcessContainer, enterprise, userAccount, campus, business);
        userProcessContainer.add("ViewMyPage", vmP);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewMyPageActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseEvent;
    private javax.swing.JButton btnMessageBox;
    private javax.swing.JButton btnViewMyPage;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JTable productTable2;
    // End of variables declaration//GEN-END:variables
}
