/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.partyRadar.memberRole;



import Business.CampusParty;
import Business.Enterprise.Enterprise;
import Business.InformationQueue.EventPost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rushabh
 */
public class ViewEventDetails extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EventPost post;
    private UserAccount userAccount;
    private CampusParty business;
    
    /** Creates new form BrowseProducts */
    public ViewEventDetails(JPanel userProcessContainer, Enterprise enterprise, EventPost post, UserAccount userAccount, CampusParty business) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.post = post;
        this.userAccount = userAccount;
        this.business = business;
        
        populate();
        changeBtnTxt();
    }
    
    private void populate(){

        lblHeader.setText(post.getEventName());
        lblHostName.setText(post.getSender().toString());
        if (post.getvPost() != null)
            lblLocation.setText(post.getvPost().toString());
        txtAreaEventDetails.setText(post.getDetails());
        String path = post.getPicPath();
        lblLikes.setText(Integer.toString(post.getLikes()));
//        ImageIcon imgIcon = new ImageIcon(path);
//        Image img = imgIcon.getImage();
//        Image smallImg = img.getScaledInstance(100,100,Image.SCALE_DEFAULT);
//        ImageIcon Icon = new ImageIcon(smallImg);
//        lblImagePreview.setIcon(Icon);
        
        populateAttendees(post);

    }
    
    private void populateAttendees(EventPost post){
        
        DefaultTableModel model = (DefaultTableModel) tblAttandees.getModel();
        model.setRowCount(0);
        
        for (UserAccount u: post.getCurrentRegister()){
           Object[] row = new Object[1];
           row[0] = u.getUsername();
           model.addRow(row);
       }

    }
    
    private void changeBtnTxt(){
        if (userAccount.favoriteEventPostContains(post)){
            btnFavorite.setText("Cancel favorite");
        } else {
            btnFavorite.setText("Favorite");
        }
        
        if (userAccount.likeEventPostContains(post)){
            btnLike.setText("Liked");
        } else {
            btnLike.setText("Like");
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAttend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEventDetails = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAttandees = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblHostName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        btnFavorite = new javax.swing.JButton();
        btnLike = new javax.swing.JButton();
        lblHeader3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblLikes = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/back.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 90, -1));

        btnAttend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/register.png"))); // NOI18N
        btnAttend.setBorderPainted(false);
        btnAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendActionPerformed(evt);
            }
        });
        add(btnAttend, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 40, 40));

        txtAreaEventDetails.setColumns(20);
        txtAreaEventDetails.setRows(5);
        jScrollPane1.setViewportView(txtAreaEventDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 240, 200));

        tblAttandees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblAttandees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblAttandees);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 240, 200));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/cancel.png"))); // NOI18N
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 40, 40));

        lblLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(102, 102, 102));
        lblLocation.setText("<show Location>");
        add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Date");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, -1));

        lblHostName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHostName.setForeground(new java.awt.Color(102, 102, 102));
        lblHostName.setText("<show Date>");
        add(lblHostName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Details:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 100, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader.setText("<Show Event Name>");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        btnFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/collect.png"))); // NOI18N
        btnFavorite.setBorder(null);
        btnFavorite.setBorderPainted(false);
        btnFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoriteActionPerformed(evt);
            }
        });
        add(btnFavorite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, 40));

        btnLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/like.png"))); // NOI18N
        btnLike.setBorder(null);
        btnLike.setBorderPainted(false);
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });
        add(btnLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 40));

        lblHeader3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader3.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Location");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("They are going:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("# Likes");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, -1));

        lblLikes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLikes.setForeground(new java.awt.Color(102, 102, 102));
        lblLikes.setText("<show Likes>");
        add(lblLikes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        Component[] components = userProcessContainer.getComponents();
        for (Component c: components){
            if (c instanceof BrowseEvents){
                BrowseEvents panel = (BrowseEvents)c;
                panel.populateEvent();
                panel.populateHotEvent();
            }
        }

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendActionPerformed

         if(userAccount.getInfoQueue().getInfoPostList().indexOf(post)<0){
            if (post.attend()){
                // Rita: add post to user's infoQueue
                userAccount.getInfoQueue().getInfoPostList().add(post);
                // Rita: add user to eventPost currentRegister
                post.addCurrentRegister(userAccount);
            } else {
                JOptionPane.showMessageDialog(null, "No remaining location!");
            }
            JOptionPane.showMessageDialog(null, "Registered successfully!");
            }
        else{
            JOptionPane.showMessageDialog(null, "You already registered.");      
        } 
         populateAttendees(post);
    }//GEN-LAST:event_btnAttendActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if(userAccount.getInfoQueue().getInfoPostList().indexOf(post)<0){               
            JOptionPane.showMessageDialog(null, "You have not registered yet!");
        }
        else{
            if (post.cancelAttend()){
                userAccount.getInfoQueue().getInfoPostList().remove(post);
                post.removeCurrentRegister(userAccount);
                JOptionPane.showMessageDialog(null, "Canceled successfully!");
                populateAttendees(post);
            } else {
                JOptionPane.showMessageDialog(null, "Cancel failure!");
            }
        }      
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoriteActionPerformed

        if (userAccount.favoriteEventPostContains(post)){
            if (userAccount.removeFavoriteEventPost(post)){
                post.reduceFavorites();
                JOptionPane.showMessageDialog(null, "Successfully canceled!");
            } else {
                JOptionPane.showMessageDialog(null, "Not saved!");
            }
        } else {
            if (userAccount.addFavoriteEventPost(this.post)){
                post.addFavorites();
                JOptionPane.showMessageDialog(null, "Succesfully saved!");
            } else {
                JOptionPane.showMessageDialog(null, "Saved!");
            }
        }
        changeBtnTxt();
    }//GEN-LAST:event_btnFavoriteActionPerformed

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        if (userAccount.likeEventPostContains(post)){
            if (userAccount.removeLikeEventPost(post)){
                post.reduceLikes();
                JOptionPane.showMessageDialog(null, "Successfully canceled!");
            } else {
                JOptionPane.showMessageDialog(null, "Not liked!");
            }
        } else {
            if (userAccount.addLikeEventPost(post)){
                post.addLikes();
                JOptionPane.showMessageDialog(null, "Like success!");
            } else {
                JOptionPane.showMessageDialog(null, "Liked!");
            }
        }
        changeBtnTxt();
    }//GEN-LAST:event_btnLikeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttend;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFavorite;
    private javax.swing.JButton btnLike;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JLabel lblHostName;
    private javax.swing.JLabel lblLikes;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JTable productTable2;
    private javax.swing.JTable tblAttandees;
    private javax.swing.JTextArea txtAreaEventDetails;
    // End of variables declaration//GEN-END:variables
}
