/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.partyRadar.memberRole;

import Business.Campus.Campus;
import Business.CampusParty;
import Business.Enterprise.Enterprise;
import Business.InformationQueue.EventPost;
import Business.InformationQueue.InformationPost;
import Business.InformationQueue.InvitationPost;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author
 */
public class ViewOthersPage extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private UserAccount selectUser;
    private Campus campus;
    private CampusParty business;
    /** Creates new form BrowseProducts */
    
    public ViewOthersPage(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, UserAccount selectUser) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.selectUser = selectUser;
        
//        this.campus = campus;
//        this.business = business;
        
        lblName.setText(selectUser.getMember().getName());
        lblNoFollowers.setText(String.valueOf(selectUser.getFollowerList().size()));
        lblNoFollowings.setText(String.valueOf(selectUser.getFollowingList().size()));
        
        populateEvent();
        
    }
    
    // dec.09: rita
    private void populateEvent(){
        DefaultTableModel model = (DefaultTableModel) tblEvent.getModel();

        model.setRowCount(0);
        for (InformationPost infoPost : selectUser.getInfoQueue().getInfoPostList()){
            if (infoPost instanceof EventPost){
                EventPost post = (EventPost) infoPost;
                Object[] row = new Object[4];
                row[0] = post;
                row[1] = post.getDate();
                row[2] = post.getvPost().toString();
                row[3] = post.getAvailableSpot();

                model.addRow(row);
            }
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblNoFollowers = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblNoFollowings = new javax.swing.JLabel();
        btnViewEventDetails1 = new javax.swing.JButton();
        btnFollow = new javax.swing.JButton();
        lblHeader2 = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/return-arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("followers");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 20));

        lblNoFollowers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoFollowers.setForeground(new java.awt.Color(102, 102, 102));
        lblNoFollowers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNoFollowers.setText("#");
        add(lblNoFollowers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 20, 20));

        btnJoin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJoin.setBorder(null);
        btnJoin.setBorderPainted(false);
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 70, -1));

        tblEvent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "My Event", "Date", "Venue", "Available Spots"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblEvent);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 530, 270));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 150, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("<show Name>");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("followings");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, 20));

        lblNoFollowings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoFollowings.setForeground(new java.awt.Color(102, 102, 102));
        lblNoFollowings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNoFollowings.setText("#");
        add(lblNoFollowings, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 20, 20));

        btnViewEventDetails1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewEventDetails1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/search.png"))); // NOI18N
        btnViewEventDetails1.setBorder(null);
        btnViewEventDetails1.setBorderPainted(false);
        btnViewEventDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEventDetails1ActionPerformed(evt);
            }
        });
        add(btnViewEventDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 50, -1));

        btnFollow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFollow.setForeground(new java.awt.Color(255, 255, 255));
        btnFollow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/follower_24.png"))); // NOI18N
        btnFollow.setBorder(null);
        btnFollow.setMaximumSize(new java.awt.Dimension(40, 40));
        btnFollow.setMinimumSize(new java.awt.Dimension(40, 40));
        btnFollow.setPreferredSize(new java.awt.Dimension(40, 40));
        btnFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowActionPerformed(evt);
            }
        });
        add(btnFollow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 30, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
// dec.09 rita:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        Component[] components = userProcessContainer.getComponents();
        for (Component c: components){
            if (c instanceof ViewMyPage){
                ViewMyPage panel = (ViewMyPage)c;
                panel.populateTree();
                panel.populateLbl();
    
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // TODO add your handling code here:
        
    int selectRow = tblEvent.getSelectedRow();
    
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        
        else {   
            InvitationPost selectPost =  (InvitationPost) tblEvent.getValueAt(selectRow, 0);
            EventPost ePost = selectPost.getEventPost();
//            userAccount.getInfoQueue().getInfoPostList().add(ePost);
//            ePost.addCurrentRegister(userAccount);
//            JOptionPane.showMessageDialog(null, "Successfully attended this event!");
//        }      
            if(userAccount.getInfoQueue().getInfoPostList().indexOf(ePost)<0){
                // Rita: add post to user's infoQueue
                userAccount.getInfoQueue().getInfoPostList().add(ePost);
                // Rita: add user to eventPost currentRegister                
                ePost.addCurrentRegister(userAccount);
                JOptionPane.showMessageDialog(null, "Registered successfully!");
            }
            else{
                JOptionPane.showMessageDialog(null, "You already registered.");
            }  
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnViewEventDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEventDetails1ActionPerformed
        // TODO add your handling code here:
           int selectRow = tblEvent.getSelectedRow();
        
        if(selectRow <0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view detials", "Warning", JOptionPane.WARNING_MESSAGE);            
        } 
        else{
            InvitationPost iPost = (InvitationPost) tblEvent.getValueAt(selectRow, 0);
            EventPost ePost = iPost.getEventPost();

            ViewEventDetails panel = new ViewEventDetails(userProcessContainer, enterprise, ePost, userAccount, business);
            userProcessContainer.add("ViewEventDetails", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewEventDetails1ActionPerformed

    private void btnFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowActionPerformed


        if (userAccount.getFollowingList().indexOf(selectUser)>=0){
            JOptionPane.showMessageDialog(null, "You are already following " + selectUser.toString() + ".");}
        
        else{
            userAccount.follow(selectUser);
            JOptionPane.showMessageDialog(null, "You are following " +  selectUser.toString() + " now!");
            lblNoFollowers.setText(String.valueOf(selectUser.getFollowerList().size()));
        }
    }//GEN-LAST:event_btnFollowActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFollow;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnViewEventDetails1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoFollowers;
    private javax.swing.JLabel lblNoFollowings;
    private javax.swing.JTable productTable2;
    private javax.swing.JTable tblEvent;
    // End of variables declaration//GEN-END:variables
}
