/*
 * ManageProductCatalogJPanel.java
 *
 * Created on September 24, 2008, 2:40 PM
 */
package UserInterface.ManageFlights;

import Business.Airliner;
import Business.Flight;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rushabh
 */
public class ManageFlightCatalogJPanel extends javax.swing.JPanel {

    JPanel container;
    Airliner airliner;  
    /** Creates new form ManageProductCatalogJPanel */
    public ManageFlightCatalogJPanel(JPanel c, Airliner a) {
        initComponents();
        container = c;
        airliner = a;
        txtAirlinerName.setText(airliner.getAirlinerName());
        refreshTable();
    }

    
    public void refreshTable() {
        
        int rowCount = flightCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel)flightCatalog.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Flight f : airliner.getFlightDirectory().getFlightDir()) {          
            Object row[] = new Object[5];
            row[0] = f;
            row[1] = f.getFlightTime();
            row[2] = f.getFlightFromLoca();
            row[3] = f.getFlightToLoca();
            row[4] = f.getAirplaneName();
            model.addRow(row);
            }
        }

    
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightCatalog = new javax.swing.JTable();
        btnViewF = new javax.swing.JButton();
        btnCreateF = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Product Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        flightCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight Name", "Flight Time", "From Location", "To Location", "Airplane"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 510, 170));

        btnViewF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewF.setText("View Flight Detail >>");
        btnViewF.setToolTipText("");
        btnViewF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFActionPerformed(evt);
            }
        });
        add(btnViewF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 220, -1));

        btnCreateF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreateF.setText("Create New Flight >>");
        btnCreateF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFActionPerformed(evt);
            }
        });
        add(btnCreateF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Airliner:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, -1));

        txtAirlinerName.setEditable(false);
        txtAirlinerName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtAirlinerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAirlinerName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(102, 102, 102), null, null));
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 150, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Delete Flight(s)");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 190, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void btnViewFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFActionPerformed
        // TODO add your handling code here:
        int row = flightCatalog.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight f = (Flight)flightCatalog.getValueAt(row, 0);
        ViewFlightDetailJPanel vfdjp = new ViewFlightDetailJPanel(container, f);
        container.add("ViewFlightDetailJPanel", vfdjp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewFActionPerformed

    private void btnCreateFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFActionPerformed
        CreateNewFlightJPanel cnfjp = new CreateNewFlightJPanel(container, airliner);
        container.add("CreateNewFlightJPanel",cnfjp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnCreateFActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = flightCatalog.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight f = (Flight)flightCatalog.getValueAt(row, 0);
        airliner.getFlightDirectory().removeFlight(f);
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateF;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewF;
    private javax.swing.JTable flightCatalog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAirlinerName;
    // End of variables declaration//GEN-END:variables
}
