/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.ManageFlights;


import Business.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class ViewFlightDetailJPanel extends javax.swing.JPanel {

    JPanel container;
    Flight flight;  
   
    
    
    /** Creates new form CreateProductJPanel */
    public ViewFlightDetailJPanel(JPanel c, Flight f) {
        initComponents();
        container = c;
        flight = f;
        txtFlightName.setText(f.getFlightName());
        txtFlightTime.setText(f.getFlightTime());
        txtFromLoca.setText(f.getFlightFromLoca());
        txtToLoca.setText(f.getFlightToLoca());
        txtAirplane.setText(f.getAirplaneName());
    }

    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFlightName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFlightTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFromLoca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtToLoca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAirplane = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Flight Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 25, -1, -1));

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreate.setText("Update Flight");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 176, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Flight Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 30));

        txtFlightName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtFlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Flight Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 30));

        txtFlightTime.setEditable(false);
        txtFlightTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtFlightTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("From Localtion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 30));

        txtFromLoca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtFromLoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("To Localtion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 30));

        txtToLoca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtToLoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Airplane:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 30));

        txtAirplane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtAirplane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
       txtFlightName.setEditable(true);
       txtFlightTime.setEditable(true);
       txtFromLoca.setEditable(true);
       txtToLoca.setEditable(true);
       txtAirplane.setEditable(true);
       btnSave.setEnabled(true);
}//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
      backAction();
    }//GEN-LAST:event_btnBackActionPerformed

      private void backAction() {
                
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightCatalogJPanel manageFlightCatalogJPanel = (ManageFlightCatalogJPanel) component;
        manageFlightCatalogJPanel.refreshTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        flight.setFlightName(txtFlightName.getText());
        flight.setFlightTime(txtFlightTime.getText());
        flight.setFlightFromLoca(txtFromLoca.getText());
        flight.setFlightToLoca(txtToLoca.getText());
        flight.setAirplaneName(txtAirplane.getText());

    }//GEN-LAST:event_btnSaveActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAirplane;
    private javax.swing.JTextField txtFlightName;
    private javax.swing.JTextField txtFlightTime;
    private javax.swing.JTextField txtFromLoca;
    private javax.swing.JTextField txtToLoca;
    // End of variables declaration//GEN-END:variables
}
