/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.venueRadar.VenueMaintainanceManagerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Venue;
import Business.Enterprise.VenueRadarEnterprise;
import Business.Group.Group;
import Business.Group.MaintainerGroup;
import Business.InformationQueue.MaintainanceRequestPost;
import Business.UserAccount.UserAccount;
import Business.Group.VenueMaintainanceManagerGroup;
import Business.InformationQueue.InformationPost;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author
 */
public class RequestMaintainancePanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;

    /** Creates new form BrowseProducts */
    public RequestMaintainancePanel(JPanel userProcessContainer, UserAccount account, VenueMaintainanceManagerGroup group, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        valueLabel.setText(enterprise.getName());
        populateCombo();
    }
    
    private void populateCombo(){
        cbVenue.removeAllItems();      
        for (Venue venue: ((VenueRadarEnterprise)enterprise).getVenueDirectory().getVenueDirectory()){
            cbVenue.addItem(venue.getVenueName());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRequestMaintainance = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbVenue = new javax.swing.JComboBox();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 90, -1));

        btnRequestMaintainance.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnRequestMaintainance.setText("Request Maintainance");
        btnRequestMaintainance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMaintainanceActionPerformed(evt);
            }
        });
        add(btnRequestMaintainance, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 140, 40));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, 30));

        txtMessage.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Venue");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 30));

        cbVenue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbVenue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 260, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_v.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setText("Maintainance Request");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMaintainanceRequestPanel mngMaintainancePanel = (ManageMaintainanceRequestPanel) component;
        mngMaintainancePanel.refreshTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestMaintainanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMaintainanceActionPerformed
        String message = txtMessage.getText();
        String place = (String)cbVenue.getSelectedItem();
        if (message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter maintainance message!");}
        
        else{
        
            MaintainanceRequestPost post = new MaintainanceRequestPost();
            post.setPlace(place);
            post.setMessage(message);
            post.setSender(account);
            post.setStatus("Sent");
            btnRequestMaintainance.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Request successfully sent!");

            Group gro = null;
            for (Group group : enterprise.getGroupDirectory().getGroupList()){
                if (group instanceof MaintainerGroup){
                    gro = group;
                    break;
                }
            }
            if (gro!=null){          
                gro.getInfoQueue().getInfoPostList().add(post);
                account.getInfoQueue().getInfoPostList().add(post);
            } 
        }

    }//GEN-LAST:event_btnRequestMaintainanceActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestMaintainance;
    private javax.swing.JComboBox cbVenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTable productTable2;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
