/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.venueRadar.venueBookingManagerRole;


import Business.Enterprise.Enterprise;
import Business.Enterprise.Venue;
import Business.Enterprise.VenueRadarEnterprise;
import Business.Group.VenueMaintainanceManagerGroup;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageVenuePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManageVenuePanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        refreshTable();
    }

//    ManageVenuePanel(JPanel userProcessContainer, UserAccount account, VenueManagerGroup group, Enterprise enterprise) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
                                      
      
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel)tblVenue.getModel();
        model.setRowCount(0);
        
        for(Venue venue: ((VenueRadarEnterprise)enterprise).getVenueDirectory().getVenueDirectory()) {           
            Object row[] = new Object[2];
            row[0] = venue;
            row[1] = venue.getVenueName();
            model.addRow(row);
        }   
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewDetails = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVenue = new javax.swing.JTable();
        btnAddVenue = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDeleteVenue = new javax.swing.JButton();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewDetails.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 110, -1));

        tblVenue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblVenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Venue Id", "Venue Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblVenue);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 500, 300));

        btnAddVenue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnAddVenue.setText("Add Venue");
        btnAddVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVenueActionPerformed(evt);
            }
        });
        add(btnAddVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 110, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 90, -1));

        btnDeleteVenue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnDeleteVenue.setText("Delete Venue");
        btnDeleteVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVenueActionPerformed(evt);
            }
        });
        add(btnDeleteVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 110, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_v.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("Venue Management");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 250, -1));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed

        
        int selectRow =tblVenue.getSelectedRow();
        if(selectRow<0) {
            JOptionPane.showMessageDialog(null,"Please selecte a row");
        }
        else{
            Venue venue = (Venue) tblVenue.getValueAt(selectRow, 0);
            ViewVenueDetailsPanel vPanel = new ViewVenueDetailsPanel (userProcessContainer, enterprise, venue);
            userProcessContainer.add("ViewVenueDetailsPanel",vPanel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnAddVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVenueActionPerformed
        // TODO add your handling code here:
        
        
        
        AddVenuePanel addVenuePanel = new AddVenuePanel(userProcessContainer,  enterprise);
        userProcessContainer.add("AddVenuePanel", addVenuePanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAddVenueActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVenueActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblVenue.getSelectedRow();       
        if(selectedRow>=0) {
            int i = JOptionPane.showConfirmDialog(null, "Are you sure to delete this venue?");
            if (i == JOptionPane.YES_OPTION){
                Venue venue = (Venue) tblVenue.getValueAt(selectedRow, 0);
                ((VenueRadarEnterprise)enterprise).getVenueDirectory().removeVenue(venue);
                refreshTable();
            }
        }
        else{
                JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnDeleteVenueActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVenue;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteVenue;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTable tblVenue;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
