/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.venueRadar.venueBookingManagerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Venue;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author
 */
public class ViewVenueDetailsPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Venue venue;

    /** Creates new form BrowseProducts */
    public ViewVenueDetailsPanel(JPanel userProcessContainer, Enterprise enterprise, Venue venue) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.venue = venue;
        
        txtVenueName.setText(venue.getVenueName());
//        txtCampus.setText(venue.getCampus());
        txtLocation.setText(venue.getLocation());
        txtLabel.setText(venue.getLabel());
        txtDetails.setText(venue.getDetails()); 
//        String path = venue.getPicPath();
//        txtPath.setText(path);
//        ImageIcon imgIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
//        lblImagePreview.setIcon(imgIcon);
//        btnChooseFile.setEnabled(false);   
        
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
        txtVenueName.setEnabled(false);
        txtLocation.setEnabled(false);
        txtLabel.setEnabled(false);
        txtDetails.setEnabled(false); 
        txtVenueName.setEditable(false);
        txtLocation.setEditable(false);
        txtLabel.setEditable(false);
        txtDetails.setEditable(false);

        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
      
    }   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        productTable2 = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtVenueName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtLabel = new javax.swing.JTextField();
        lblHeader2 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();

        productTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productTable2);

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(750, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 130, 30));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 90, -1));

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, 130, 30));

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        txtDetails.setEnabled(false);
        jScrollPane1.setViewportView(txtDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 340, 190));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Venue Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Location");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 100, -1));

        txtVenueName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenueNameActionPerformed(evt);
            }
        });
        add(txtVenueName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 340, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Label");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 140, -1));
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 340, 20));
        add(txtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 340, 20));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_v.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("Venue Booking Work Area");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 320, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
        
        Component[] components = userProcessContainer.getComponents();
        for (Component c: components){
            if (c instanceof ManageVenuePanel){
                ManageVenuePanel panel = (ManageVenuePanel)c;
                panel.refreshTable();
            }
        }

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtVenueNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenueNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenueNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String venueName = txtVenueName.getText();
//        String campus = txtCampus.getText();
        String location = txtLocation.getText();
        String label = txtLabel.getText();
        String details = txtDetails.getText();    
//        String path = txtPath.getText();

        if (venueName.isEmpty()||location.isEmpty()||label.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please complete all the mandatory fields!");
            } 
        else {              
            venue.setVenueName(venueName);
//            venue.setCampus(campus);
            venue.setLocation(location);
            venue.setLabel(label);
            venue.setDetails(details);
//            venue.setPicPath(path);

            JOptionPane.showMessageDialog(null, "Updates successfully saved!");
        }   
        
         txtVenueName.setEnabled(false);
//        txtCampus.setEditable(true);
        txtLocation.setEnabled(false);
        txtLabel.setEnabled(false);
//        txtPath.setEnabled(false);
        txtDetails.setEnabled(false); 
        btnEdit.setEnabled(false);
        btnSave.setEnabled(false);
//        btnChooseFile.setEnabled(false);
       
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);        
    }//GEN-LAST:event_btnSaveActionPerformed

    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        txtVenueName.setEditable(true);
        txtLocation.setEditable(true);
        txtLabel.setEditable(true);
        txtDetails.setEditable(true);
        
        txtVenueName.setEnabled(true);
        txtLocation.setEnabled(true);
        txtLabel.setEnabled(true);
        txtDetails.setEnabled(true);

        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);

    }//GEN-LAST:event_btnEditActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTable productTable2;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtLabel;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtVenueName;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
