/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.venueRadar.cateringManagerRole;

import Business.Enterprise.CateringMenu;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Venue;
import Business.Enterprise.VenueRadarEnterprise;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bonnie
 */
public class ViewMenuDetailsPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    CateringMenu menu;
    
    /**
     * Creates new form ViewMenuDetailsPanel
     */
    public ViewMenuDetailsPanel(JPanel userProcessContainer, Enterprise enterprise, CateringMenu menu) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.menu = menu;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());

        
        txtCateringName.setText(menu.getCateringName());
        txtType.setText(menu.getType());
//        txtLocation.setText(venue.getLocation());
      //  txtPath.setText(menu.getLabel());
        txtDetails.setText(menu.getDetails()); 
        String path = menu.getPicPath();
        ImageIcon imgIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
//        lblImagePreview.setIcon(imgIcon);
        
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
//        btnChooseFile.setEnabled(false);
    }

//    ViewMenuDetailsPanel(JPanel userProcessContainer, Enterprise enterprise, CateringMenu menu) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

//    ViewMenuDetailsPanel(JPanel userProcessContainer, Enterprise enterprise, ViewMenuDetailsPanel vmPanel) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        txtCateringName = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblHeader3 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Catering Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 30));

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        txtDetails.setEnabled(false);
        jScrollPane1.setViewportView(txtDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 300, 190));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Menu Type");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 30));

        txtCateringName.setEnabled(false);
        txtCateringName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCateringNameActionPerformed(evt);
            }
        });
        add(txtCateringName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 300, 30));

        txtType.setEnabled(false);
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 300, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 100, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 90, -1));

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 130, 30));

        lblHeader3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader3.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_v.png"))); // NOI18N
        lblHeader3.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 70));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader2.setText("Catering Process Request");
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 380, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String menuName = txtCateringName.getText();
        String type = txtType.getText();
        String details = txtDetails.getText();

        if (menuName.isEmpty()||type.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add all the mandatory fields!");
        }
        else {
//            CateringMenu menu = ((VenueRadarEnterprise)enterprise).getMenuDirectory().addCateringMenu();
            menu.setCateringName(menuName);
            menu.setType(type);
            menu.setDetails(details);
//            menu.setPicPath(path);

            JOptionPane.showMessageDialog(null, "Updates successfully saved!");

        }
        txtCateringName.setEnabled(false);
        txtType.setEnabled(false);
        txtDetails.setEnabled(false);
//        txtPath.setEnabled(false);
        
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
//        btnChooseFile.setEnabled(false);
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCateringNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCateringNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCateringNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);

        Component[] components = userProcessContainer.getComponents();
        for (Component c: components){
            if (c instanceof ManageCateringPanel){
                ManageCateringPanel panel = (ManageCateringPanel)c;
                panel.refreshTable();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtCateringName.setEnabled(true);
        txtType.setEnabled(true);
//        txtPath.setEnabled(true);
        txtDetails.setEnabled(true); 
        
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
//        btnChooseFile.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JTextField txtCateringName;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtType;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
