/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.CampusParty;
import Business.Enterprise.Enterprise;
import Business.Campus.Campus;
import Business.Member.Member;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */

public class ManageEnterpriseAdminPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CampusParty system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminPanel(JPanel userProcessContainer, CampusParty system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateCampusComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();

        model.setRowCount(0);
        for (Campus campus : system.getCampusList()) {
            for (Enterprise enterprise : campus.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount: enterprise.getUserAccountDirectory().getUserAccountList()){
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = campus.getName();
                row[2] = userAccount.getUsername();

                model.addRow(row);
                }
            }
        }
    }
    
    private void populateCampusComboBox(){
        cbCampus.removeAllItems();
        
        for (Campus campus: system.getCampusList()){
            cbCampus.addItem(campus);
        }
    }
    
    private void populateEnterpriseComboBox(Campus campus){
        cbEnterpriseType.removeAllItems();
        
        for (Enterprise enterprise : campus.getEnterpriseDirectory().getEnterpriseList()){
            cbEnterpriseType.addItem(enterprise);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbCampus = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbEnterpriseType = new javax.swing.JComboBox();
        txtUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        pswdField = new javax.swing.JPasswordField();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setPreferredSize(new java.awt.Dimension(600, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));

        tblEnterprise.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 225, 470, 180));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Campus");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, 30));

        cbCampus.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbCampus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCampusActionPerformed(evt);
            }
        });
        add(cbCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 280, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, 40));

        cbEnterpriseType.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 280, 27));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 280, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Username");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, 30));

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, 30));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 280, 27));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, 91, -1));

        pswdField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(pswdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 280, 27));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_t.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 70));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("Enterprise Admin Management");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 340, -1));
    }// </editor-fold>//GEN-END:initComponents
                                    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        Enterprise enterprise = (Enterprise) cbEnterpriseType.getSelectedItem();
        
        String username = txtUserName.getText();
        String password = String.valueOf(pswdField.getPassword());
        String name = txtName.getText();
        Member member = enterprise.getMemberDirectory().createMember(name);
        if (username.isEmpty() || password.isEmpty() || name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill in completely!");
            return;
        }
        for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()){
            if (ua.getUsername().equals(username)){
                JOptionPane.showMessageDialog(null, "Already created!");
                return;
            }
        }
        UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, member, new AdminRole());

        populateTable();
        txtUserName.setText(null);
        pswdField.setText(null);
        txtName.setText(null);
        JOptionPane.showMessageDialog(null, "Created successfully!");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cbCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCampusActionPerformed
        
        Campus campus = (Campus) cbCampus.getSelectedItem();
        if (campus != null){
            populateEnterpriseComboBox(campus);
        }// TODO add your handling code here:
    }//GEN-LAST:event_cbCampusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaPanel sysAdminWA = (SystemAdminWorkAreaPanel) component;
        sysAdminWA.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cbCampus;
    private javax.swing.JComboBox cbEnterpriseType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JPasswordField pswdField;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
