/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.CampusParty;
import Business.Enterprise.Enterprise;
import Business.Campus.Campus;
import Business.Group.Group;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    CampusParty system;
    
    public SystemAdminWorkAreaPanel(JPanel userProcessContainer,CampusParty system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        ArrayList<Campus> campusList=system.getCampusList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Group> groupList;
        
        Campus campus;
        Enterprise enterprise;
        Group group;
        
        DefaultMutableTreeNode campuses = new DefaultMutableTreeNode("Campuses");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(campuses, 0);
        
        DefaultMutableTreeNode campusNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode groupNode;
        
        for(int i=0;i<campusList.size();i++){
            campus=campusList.get(i);
            campusNode=new DefaultMutableTreeNode(campus.getName());
            campuses.insert(campusNode, i);
            
            enterpriseList=campus.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                campusNode.insert(enterpriseNode, j);
                
                groupList=enterprise.getGroupDirectory().getGroupList();
                for(int k=0;k<groupList.size();k++){
                    group=groupList.get(i);
                    groupNode=new DefaultMutableTreeNode(group.getName());
                    enterpriseNode.insert(groupNode, k);
                }
            }
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();
        btnMngCampus = new javax.swing.JButton();
        btnMngEnterpriseAdmin = new javax.swing.JButton();
        btnMngEnterprise = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();
        lblHeader2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 1000));

        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 1000));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Selected Node:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        lblSelectedNode.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblSelectedNode.setForeground(new java.awt.Color(102, 102, 102));
        lblSelectedNode.setText("<View_selected_node>");
        jPanel2.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        btnMngCampus.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnMngCampus.setText(">> Manage Campus");
        btnMngCampus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMngCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCampusActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 290, 40));

        btnMngEnterpriseAdmin.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnMngEnterpriseAdmin.setText(">> Manage Enterprise Admin");
        btnMngEnterpriseAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMngEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEnterpriseAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngEnterpriseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 290, 40));

        btnMngEnterprise.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnMngEnterprise.setText(">> Manage Enterprise");
        btnMngEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMngEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEnterpriseActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 290, 40));

        btnAnalysis.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAnalysis.setText(">> Analytic Dashboard");
        btnAnalysis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 290, 42));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_t.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        jPanel2.add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 340, 70));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        
        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
        if(selectedNode!=null){
            lblSelectedNode.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_jTreeValueChanged

    private void btnMngEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEnterpriseActionPerformed
        // TODO add your handling code here:                                  
        ManageEnterprisePanel manageEnterprisePanel=new ManageEnterprisePanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterprisePanel",manageEnterprisePanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);     

    }//GEN-LAST:event_btnMngEnterpriseActionPerformed

    private void btnMngCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCampusActionPerformed
        ManageCampusPanel manageCampusPanel=new ManageCampusPanel(userProcessContainer, system);
        userProcessContainer.add("manageCampusPanel",manageCampusPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnMngCampusActionPerformed

    private void btnMngEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEnterpriseAdminActionPerformed
        ManageEnterpriseAdminPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
   
    }//GEN-LAST:event_btnMngEnterpriseAdminActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        AnalysisPanel panel = new AnalysisPanel(userProcessContainer, system);
        userProcessContainer.add("AnalysisPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnMngCampus;
    private javax.swing.JButton btnMngEnterprise;
    private javax.swing.JButton btnMngEnterpriseAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
