/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.Agency.FlightSchedule;


import Business.Airliner;
import UserInterface.Customer.*;
import Business.Customer;
import UserInterface.ManageFlights.*;
import Business.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class MasterFlightDetailJPanel extends javax.swing.JPanel {

    JPanel container;
    Flight flight;  
    Customer customer;
    Airliner airliner;
   
    
    
    /** Creates new form CreateProductJPanel */
    public MasterFlightDetailJPanel(JPanel c, Flight f) {
        initComponents();
        container = c;
        customer = new Customer();
        this.flight = f;
     
        txtFlightName.setText(f.getFlightName());
        txtFlightTime.setText(f.getFlightTime());
        txtFromLoca.setText(f.getFlightFromLoca());
        txtToLoca.setText(f.getFlightToLoca());
        txtAirplane.setText(f.getAirplaneName());
    }

    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFlightName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFlightTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFromLoca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtToLoca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAirplane = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Flight Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 25, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Flight Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 30));

        txtFlightName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtFlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Flight Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 30));

        txtFlightTime.setEditable(false);
        txtFlightTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtFlightTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("From Localtion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 30));

        txtFromLoca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtFromLoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("To Localtion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 30));

        txtToLoca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtToLoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Airplane:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 30));

        txtAirplane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtAirplane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 210, -1));

        btnBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBook.setText("Book Flight");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 176, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        BookFlightJPanel bfjp = new BookFlightJPanel(container, customer, flight);
        container.add("BookFlightJPanel",bfjp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
}//GEN-LAST:event_btnBookActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
      backAction();
    }//GEN-LAST:event_btnBackActionPerformed

      private void backAction() {
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MasterFlightJPanel masterFlightJPanel = (MasterFlightJPanel) component;
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
            }   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAirplane;
    private javax.swing.JTextField txtFlightName;
    private javax.swing.JTextField txtFlightTime;
    private javax.swing.JTextField txtFromLoca;
    private javax.swing.JTextField txtToLoca;
    // End of variables declaration//GEN-END:variables
}
