

package userinterface.AdministrativeRole;


import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngUsers = new javax.swing.JButton();
        btnMngGroup = new javax.swing.JButton();
        btnMngAccount = new javax.swing.JButton();
        lblHeader2 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMngUsers.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnMngUsers.setText(">> Manage Users");
        btnMngUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUsersActionPerformed(evt);
            }
        });
        add(btnMngUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 330, 40));

        btnMngGroup.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnMngGroup.setText(">> Manage Group");
        btnMngGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngGroupActionPerformed(evt);
            }
        });
        add(btnMngGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 330, 40));

        btnMngAccount.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnMngAccount.setText(">> Manage Account");
        btnMngAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAccountActionPerformed(evt);
            }
        });
        add(btnMngAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 330, 40));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_t.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 70));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setText("Admin Work Area");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngGroupActionPerformed

        ManageGroupPanel manageGroupPanel = new ManageGroupPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageGroupPanel", manageGroupPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngGroupActionPerformed

    private void btnMngUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUsersActionPerformed
        
        ManageUserPanel manageUserPanel = new ManageUserPanel(userProcessContainer, enterprise.getGroupDirectory(), enterprise);
        userProcessContainer.add("manageUserPanel", manageUserPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngUsersActionPerformed

    private void btnMngAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAccountActionPerformed
        
        ManageAccountPanel majp = new ManageAccountPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageAccountJPanel", majp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngAccountActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngAccount;
    private javax.swing.JButton btnMngGroup;
    private javax.swing.JButton btnMngUsers;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
