/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Group.Group;
import Business.Group.Group.Type;
import Business.Group.GroupDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageGroupPanel extends javax.swing.JPanel {

    private GroupDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    /**
     * Creates new form ManageGroupJPanel
     */
    public ManageGroupPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = enterprise.getGroupDirectory();
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        cbGroup.removeAllItems();
        EnterpriseType enterpriseType = enterprise.getEnterpriseType();
        // PartyRadar只能选择EventManager和PlatformMember
        if (enterpriseType.getValue().equals(EnterpriseType.PartyRadar.getValue())){
            for (Type type : Group.Type.values()){
                if (type.getValue().equals(Type.EventManager.getValue()) || type.getValue().equals(Type.PlatformMember.getValue())){
                    if (!type.getValue().equals(Type.Admin.getValue()))
                        cbGroup.addItem(type);
                }
            }
        }
        // VenueRadar只能选择
        if (enterpriseType.getValue().equals(Enterprise.EnterpriseType.VenueRadar.getValue())){
            for (Type type : Group.Type.values()){
                if (type.getValue().equals(Type.VenueMaintainanceManager.getValue()) ||type.getValue().equals(Type.VenueBookingManager.getValue())|| type.getValue().equals(Type.Maintainer.getValue())|| type.getValue().equals(Type.CateringManager.getValue())){
                    if (!type.getValue().equals(Type.Admin.getValue()))
                        cbGroup.addItem(type);
                }
            }
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblGroup.getModel();
        
        model.setRowCount(0);
        
        for (Group group : directory.getGroupList()){
            Object[] row = new Object[2];
            row[0] = group.getGroupID();
            row[1] = group.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGroup = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        cbGroup = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGroup.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGroup);
        if (tblGroup.getColumnModel().getColumnCount() > 0) {
            tblGroup.getColumnModel().getColumn(0).setResizable(false);
            tblGroup.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 450, 240));

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 80, -1));

        cbGroup.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 270, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Group Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, -1, -1));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("Group Management");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 220, -1));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_t.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        Type type = (Type) cbGroup.getSelectedItem();
        directory.createGroup(type);
        populateTable();
        JOptionPane.showMessageDialog(null, "Created successfully!");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cbGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTable tblGroup;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
