/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Group.Group;
import Business.Member.Member;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ManageAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;

    public ManageAccountPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        valueLabel.setText(enterprise.getName());

        popGroupComboBox();
       // memberJComboBox.removeAllItems();
        popData();
    }

    public void popGroupComboBox() {
        cbGroup.removeAllItems();

        for (Group group : enterprise.getGroupDirectory().getGroupList()) {
            cbGroup.addItem(group);
        }
    }
    
    public void populateMemberComboBox(Group group){
        cbName.removeAllItems();
        
        for (Member member : group.getMemberDirectory().getMemberList()){
            cbName.addItem(member);
        }
    }
    
    private void populateRoleComboBox(Group group){
        cbRole.removeAllItems();
        for (Role role : group.getSupportedRole()){
            cbRole.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) btlUser.getModel();

        model.setRowCount(0);

        for (Group group : enterprise.getGroupDirectory().getGroupList()) {
            for (UserAccount ua : group.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua.getUsername();
                row[1] = ua.getRole();
                ((DefaultTableModel) btlUser.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatAccount = new javax.swing.JButton();
        txtAccountName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btlUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbGroup = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreatAccount.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCreatAccount.setText("Create");
        btnCreatAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatAccountActionPerformed(evt);
            }
        });
        add(btnCreatAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, -1, -1));

        txtAccountName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(txtAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 230, 27));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, -1));

        btlUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btlUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(btlUser);
        if (btlUser.getColumnModel().getColumnCount() > 0) {
            btlUser.getColumnModel().getColumn(0).setResizable(false);
            btlUser.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 420, 179));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 230, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        cbName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNameActionPerformed(evt);
            }
        });
        add(cbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 230, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Group");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        cbGroup.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGroupActionPerformed(evt);
            }
        });
        add(cbGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 230, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Role");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        cbRole.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 230, 27));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, -1, -1));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 102, 102));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 30));

        lblHeader1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader1.setText("Account Management");
        add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 220, -1));

        lblHeader2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(204, 0, 0));
        lblHeader2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/partyRadar/memberRole/logo_t.png"))); // NOI18N
        lblHeader2.setPreferredSize(new java.awt.Dimension(400, 124));
        add(lblHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatAccountActionPerformed
        String userName = txtAccountName.getText();
        String password = txtPassword.getText();
        if (userName.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Can not be empty!");
            return;
        }
        Group group = (Group) cbGroup.getSelectedItem();
        Member member = (Member) cbName.getSelectedItem();
        Role role = (Role) cbRole.getSelectedItem();
        for (UserAccount ua : group.getUserAccountDirectory().getUserAccountList()){
            if (ua.getUsername().equals(userName)){
                JOptionPane.showMessageDialog(null, "Already created!");
                return;
            }
        }

//       UserAccount u = 
        group.getUserAccountDirectory().createUserAccount(userName, password, member, role);
        
//        //Rita: relate member and userAccount
//        member.setAccount(u);
        

        popData();
        
        txtAccountName.setText(null);
        txtPassword.setText(null);
        JOptionPane.showMessageDialog(null, "Created successfully!");
    }//GEN-LAST:event_btnCreatAccountActionPerformed

    private void cbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGroupActionPerformed
        Group group = (Group) cbGroup.getSelectedItem();
        if (group != null){
            populateMemberComboBox(group);
            populateRoleComboBox(group);
        }
    }//GEN-LAST:event_cbGroupActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNameActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatAccount;
    private javax.swing.JComboBox cbGroup;
    private javax.swing.JComboBox cbName;
    private javax.swing.JComboBox cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
